# Generated by Django 3.1.5 on 2021-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='novel',
            field=models.CharField(choices=[('Poor Folk', 'Poor Folk'), ('The Double', 'The Double'), ('The Landlady', 'The Landlady'), ('Netochka Nezvanova', 'Netochka Nezvanova'), ("Unclue's Dream", "Unclue's Dream"), ('The Village of Stepanchikovo', 'The Village of Stepanchikovo'), ('Humiliated and Insulted', 'Humiliated and Insulted'), ('The House of the Dead', 'The House of the Dead'), ('Notes from Underground', 'Notes from Underground'), ('Crime and Punishment', 'Crime and Punishment'), ('The Gambler', 'The Gambler'), ('The Idiot', 'The Idiot'), ('The Eternal Husband', 'The Eternal Husband'), ('The Possessed', 'The Possessed'), ('The Adolescent', 'The Adolescent'), ('The Brothers Karamazon', 'The Brothers Karamazon')], default=1, max_length=28),
            preserve_default=False,
        ),
    ]
